### ISSUE TITLE
Error message on MacOS

### ISSUE THREAD

**Issue by THE-R4U** [r-lib/whoami#16]
When I run 'email_address()', I got an error message as below:

Error in fallback_or_stop(fallback, "Cannot get email address") : 
  Cannot get email address

**Comment by gaborcsardi** [comment]
Sometimes there is just no way to determine your email address automatically. Why do you think this is an error? 

Note that you can always set the `EMAIL` environment variable as the default.

**Comment by THE-R4U** [comment]
Thank you for your reply. 
Then, can you tell me how to set the EMAIL env. variable as the default?

**Comment by gaborcsardi** [comment]
See `?Startup` and the parts about `.Renviron` files. 

Put 
```
EMAIL=<your-email-address>
```
in `~/.Renviron`.

**Comment by THE-R4U** [comment]
Many thanks!
