### ISSUE TITLE
Error in fallback_or_stop(fallback, "Cannot find GitHub username for email") :    object 'fallback' not found

### ISSUE THREAD

**Issue by j450h1** [r-lib/whoami#17]
```
library(whoami)
whoami()
```
**Error in fallback_or_stop(fallback, "Cannot find GitHub username for email") : 
  object 'fallback' not found**

Looks like it can't find my github account name.

**Comment by gaborcsardi** [comment]
Yeah, I can reproduce this on a machine without git.

**Comment by gaborcsardi** [comment]
This is indeed closed by #17, at least `whoami()` now works w/o git, if the email address and the full can be found somehow.
