### ISSUE TITLE
on windows fullname() returns "No Instance(s) Available" 

### ISSUE THREAD

**Issue by ElenaSal55** [r-lib/whoami#23]
Dear whoami developers, 

great package, thank you. Unfortunately, I have to report a problem on Windows with whoami.
I am using the version 1.3.0 of whoami. 

About my system:
```
> sessionInfo()
R version 4.3.1 (2023-06-16 ucrt)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19044)
```

If called on a Windows machine that has no connection to his domain controller (maybe the reason, but I have no possibility to check if connecting it to the domain controller fixes the issue soon), `whoami::fullname()` does not return the username (except if specified in Git), but `"No Instance(s) Available"` instead. 

![issue2](https://github.com/r-lib/whoami/assets/51724507/d8cb0d8f-0b26-466a-a392-721e130084a9)

![issue1](https://github.com/r-lib/whoami/assets/51724507/0d4e8427-9ea0-4517-963b-02c40aef3e5f)

To work around this bug, I have configured my git name, but less advanced users may not even have git. 
Thank you for your help,

**Comment by gaborcsardi** [comment]
You can set the `FULLNAME` environment variable to work around the case when it is not possible to find it.
