### ISSUE TITLE
whoami functions not working on Windows

### ISSUE THREAD

**Issue by maelle** [r-lib/whoami#4]
I'm having issues getting `whoami` to find who I am on Windows 😉 

``` r
whoami::email_address()
#> Error in fallback_or_stop(fallback, "Cannot get email address"): Cannot get email address
whoami::fullname()
#> Error in fallback_or_stop(fallback, "Cannot determine full name"): Cannot determine full name
whoami::gh_username()
#> Error in fallback_or_stop(fallback, "Cannot get GitHub username"): Cannot get GitHub username
whoami::username()
#> [1] "maelle"
whoami::whoami()
#> Error in fallback_or_stop(fallback, "Cannot determine full name"): Cannot determine full name
```

Created on 2018-06-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.0 (2018-04-23)
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  tz       Europe/Paris                
#>  date     2018-06-25
#> Packages -----------------------------------------------------------------
#>  package   * version    date       source                            
#>  backports   1.1.2      2017-12-13 CRAN (R 3.5.0)                    
#>  base      * 3.5.0      2018-04-23 local                             
#>  compiler    3.5.0      2018-04-23 local                             
#>  datasets  * 3.5.0      2018-04-23 local                             
#>  devtools    1.13.5     2018-02-18 CRAN (R 3.5.0)                    
#>  digest      0.6.15     2018-01-28 CRAN (R 3.5.0)                    
#>  evaluate    0.10.1     2017-06-24 CRAN (R 3.5.0)                    
#>  graphics  * 3.5.0      2018-04-23 local                             
#>  grDevices * 3.5.0      2018-04-23 local                             
#>  htmltools   0.3.6.9001 2018-06-16 Github (rstudio/htmltools@3aee819)
#>  httr        1.3.1      2017-08-20 CRAN (R 3.5.0)                    
#>  jsonlite    1.5        2017-06-01 CRAN (R 3.5.0)                    
#>  knitr       1.20       2018-02-20 CRAN (R 3.5.0)                    
#>  magrittr    1.5        2014-11-22 CRAN (R 3.5.0)                    
#>  memoise     1.1.0      2017-04-21 CRAN (R 3.5.0)                    
#>  methods   * 3.5.0      2018-04-23 local                             
#>  R6          2.2.2      2017-06-17 CRAN (R 3.5.0)                    
#>  Rcpp        0.12.17    2018-05-18 CRAN (R 3.5.0)                    
#>  rmarkdown   1.9        2018-03-01 CRAN (R 3.4.4)                    
#>  rprojroot   1.3-2      2018-01-03 CRAN (R 3.4.3)                    
#>  stats     * 3.5.0      2018-04-23 local                             
#>  stringi     1.2.2      2018-05-02 CRAN (R 3.5.0)                    
#>  stringr     1.3.1      2018-05-10 CRAN (R 3.5.0)                    
#>  tools       3.5.0      2018-04-23 local                             
#>  utils     * 3.5.0      2018-04-23 local                             
#>  whoami      1.1.2      2018-06-25 Github (r-lib/whoami@d719e8c)     
#>  withr       2.1.2      2018-03-15 CRAN (R 3.4.4)                    
#>  yaml        2.1.19     2018-05-01 CRAN (R 3.5.0)
```

</details>

``` r
system("git config --global user.email", intern = TRUE)
#> Warning in system("git config --global user.email", intern = TRUE): running
#> command 'git config --global user.email' had status 1
#> character(0)
#> attr(,"status")
#> [1] 1
```

The above works when typed in a command line. 

Here's where my git config file lives:

``` r
git2r::git_config_files()$global
#> [1] "C:/Users/Maelle/.gitconfig"
```

**Comment by gaborcsardi** [comment]
git is probably not in your path.

**Comment by maelle** [comment]
I think I'm missing something: I can use the same command in the command line, doesn't it mean git is in my PATH?

**Comment by maelle** [comment]
That said in my PATH I only see "C:\Users\Program Files\Git\cmd", maybe I need something else, will look. When I find out the problem are you interested in my adding a few lines to `whoami` README about this?

**Comment by gaborcsardi** [comment]
Not for R, it seems, otherwise
```r
system("git config --global user.email", intern = TRUE)
```
would succeed. 

```
Sys.which("git")
```
will tell you.

Maybe you just need to restart R, to pick up the new path, or maybe you are running the the git-terminal, which of course has git in the path...

**Comment by maelle** [comment]
``` r
Sys.which("git")
#>                               git 
#> "C:\\PROGRA~1\\Git\\cmd\\git.exe"
```

And there's a git executable at that path. 🤔

**Comment by gaborcsardi** [comment]
Then `user.email`, etc.  are maybe  not  configured?

**Comment by maelle** [comment]
They are as far as I can tell: 

![image](https://user-images.githubusercontent.com/8360597/41844081-6b24486a-786f-11e8-9b4a-ccbe87749124.png)

The git in PATH and the git found by `Sys.which("git")` are not the same ("C:\Users\Program Files\Git\cmd" vs "C:\\PROGRA~1\\Git\\cmd\\git.exe"), not sure if this is normal.

**Comment by maelle** [comment]
For the record am reading https://github.com/jennybc/happy-git-with-r/issues/8 although it was about Mac OS.

**Comment by gaborcsardi** [comment]
For the email address whoami just runs this:
```r
system("git config --global user.email", intern = TRUE)
```
If this fails, there is not much it can do.

**Comment by maelle** [comment]
Of course, it's probably more a setup issue on my laptop, but might be interested to document in case someone else encounters the problem?

**Comment by maelle** [comment]
I'm finding clues, it's not because of git, it's because of where gitconfig is.

``` r
system("git config --global --list", intern = TRUE)
#> "fatal: unable to read config file '/.gitconfig': No such file or directory"
```

**Comment by maelle** [comment]
Am adding a symlink à la http://happygitwithr.com/ssh-keys.html#ssh-troubleshooting, will report back (doesn't really work yet).

**Comment by maelle** [comment]
So the symlink didn't work 🤷‍♀️ but copying my .gitconfig in Documents 

```r
fs::file_copy(path = "C:\\Users\\Maelle\\.gitconfig", new_path = "C:\\Users\\Maelle\\Documents\\.gitconfig")
```
did (suboptimal but well, it works). 

Interested in a "what if `whoami` doesn't work for you on Windows" subsection in your README @gaborcsardi ? Otherwise I'll just close and document elsewhere. 👼

**Comment by gaborcsardi** [comment]
I would try to make whoami / git look there as well, first.

**Comment by maelle** [comment]
what do you mean, a whoami new feature?

Now I only get an error for email like @tdjames1 https://github.com/ropenscilabs/pkgreviewr/issues/43#issuecomment-399919971 -- should `whoami` also use gitconfig for the email?

**Comment by gaborcsardi** [comment]
From `git config --help`:

```
ENVIRONMENT
       GIT_CONFIG
           Take the configuration from the given file instead of .git/config. Using
           the "--global" option forces this to ~/.gitconfig. Using the "--system"
           option forces this to $(prefix)/etc/gitconfig.
```

**Comment by maelle** [comment]
ok but currently I can't do that with `whoami` right?

I'll open a second issue for the other problem.

**Comment by gaborcsardi** [comment]
That issue is about `whoami::gh_username`, which we cannot fix, AFAIK.

**Comment by maelle** [comment]
I'm sorry that this thread got messy because of me.

>I would try to make whoami / git look there as well, first.

What do you mean with that?

**Comment by gaborcsardi** [comment]
whami should look in `Documents`, if it cannot find anything  in the standard place.

**Comment by maelle** [comment]
ok when I'm done with the 1st PR I think I can solve this too. :-)

**Comment by maelle** [comment]
I think this can be closed once you've re-knit the README @gaborcsardi 😺
