### ISSUE TITLE
gh_username

### ISSUE THREAD

**Issue by maelle** [r-lib/whoami#5]
I get an error for email like @tdjames1 https://github.com/ropenscilabs/pkgreviewr/issues/43#issuecomment-399919971  to be clear

``` r
whoami::email_address()
#> [1] "maelle.salmon@yahoo.se"
whoami::fullname()
#> [1] "MaÃ«lle Salmon"
whoami::gh_username()
#> Error in fallback_or_stop(fallback, "Cannot find GitHub username for email"): Cannot find GitHub username for email
whoami::username()
#> [1] "maelle"
whoami::whoami()
#> Error in fallback_or_stop(fallback, "Cannot find GitHub username for email"): Cannot find GitHub username for email
```

Created on 2018-06-25 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by maelle** [comment]
I actually set my username as `USERNAME` in .Renviron to be my GitHub username (because my username on my laptop is "Maelle" not "maelle").

**Comment by gaborcsardi** [comment]
We cannot look up the username from the email if the email is not public on GH.

**Comment by maelle** [comment]
yes but should/could `whoami` fall back on username in that case or could one set up a `GH_USERNAME` global variable?

**Comment by gaborcsardi** [comment]
I don't think it should fall back to the username. A fallback option/env var would make sense.

**Comment by maelle** [comment]
Should I make a PR?

**Comment by gaborcsardi** [comment]
Sure, thanks!

**Comment by maelle** [comment]
One PR encompassing the other issue, or two PRs? 😺

**Comment by gaborcsardi** [comment]
Two PRs please. Thanks!

**Comment by maelle** [comment]
I'll let you knit the README.Rmd otherwise I will become the example user 😉
